# Site settings
title: Zeeman Chen的个人博客
email: Zeeman.chen@arklouder.com
description: > # this means to ignore newlines until "baseurl:"
 Zeeman的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.arklouder.com" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: arkloud
# weibo:    ID
github: z2
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: https://c.na7.content.force.com/servlet/servlet.ImageServer?id=015A0000005Y2kP&oid=00DA0000000bEqp&lastMod=1457843518000
favicon: 

# disqus 设置
disqus:
  shortname: blogarkloudercom

# google analytics 设置
ga:
  id: UA-75011256-1
  url: blog.arklouder.com

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
